initial commit
bookmd/nconf-credstash pull request #1
Opened 2017-02-15 11:28 UTC by meirshal

2017-02-15 14:07 UTC, asafdav requested changes

2017-02-15 14:07 UTC, asafdav commented on .gitignore
> +# Logs
any reason for this project to be private instead of public ?

2017-02-15 14:07 UTC, asafdav commented on README.md
> +## Running tests
Awesome !

2017-02-15 14:07 UTC, asafdav commented on lib/nconf-credstash.js
> +function Credstash (options) {
why didn't you use ES6 ?

2017-02-15 14:07 UTC, asafdav commented on lib/nconf-credstash.js
> +    this.cmdArgs.concat([TABLE_FLAG, this.table]);
nice, might be nicer to add a small util method _addParam that hides cmdArgs for you, 
something like ```_addParam(TABLE_FLAF, this.table)```

2017-02-15 14:07 UTC, asafdav commented on lib/nconf-credstash.js
> +    this.cmdArgs.concat(['environemt='+this.environment]);
isn't there a -e flag ?

2017-02-15 14:07 UTC, asafdav commented on lib/nconf-credstash.js
> +Credstash.prototype.get = function (key) {
Out of curiosity did you think about using https://github.com/roylines/node-credstash or any other OS project?

2017-02-15 14:07 UTC, asafdav commented on lib/nconf-credstash.js
> +Credstash.prototype.get = function (key) {
anyway, i think it would be nicer to take the implementation of credstash's api out of the plugin and move it to a separate file

2017-02-15 14:07 UTC, asafdav commented on lib/nconf-credstash.js
> +  path = nconf.path(key); // convert the key (delimited by ':') to a path array.
not sure that's the right place for it

2017-02-15 14:07 UTC, asafdav commented on spec/lib/config.json
> +{
do you need this ?

2017-02-15 14:07 UTC, asafdav commented on spec/lib/privateMethods.spec.js
> +      Credstash.prototype._insertIntoStore.call(storeHolder, path, value);
Nice that you could do that right ? :)

2017-02-15 14:07 UTC, asafdav commented on spec/lib/privateMethods.spec.js
> +});
Now I understand what you mean with nconf, you had to do a lot of heavy lifting that you probably should have get from them.

2017-02-15 14:07 UTC, asafdav commented on spec/lib/privateMethods.spec.js
> +    it('should add a new key with the specified value', function() {
'it' and 'should' contradicts each other, you should phrase tests assuming this is what happens (that's the describe,it flavor), for example: it adds a new key with the specified value.

2017-02-15 14:07 UTC, asafdav commented on spec/lib/nconf-credstash.spec.js
> +describe('nconf-credstash', function() {
I'm not sure I get it, but does it use our "live" credstash to store credentials ? we need an alternative for that

2017-02-15 20:17 UTC, meirshal commented on .gitignore
> +# Logs
No, I think it definitely should be, but wasn't sure if that's OK.

2017-02-15 20:22 UTC, meirshal commented on lib/nconf-credstash.js
> +function Credstash (options) {
I thought about it. 
Basically I wanted the code to be as simple as possible, so that we can open source it if want to. So I wanted it to be just a simple node module, without a complex build with babel and gulp.
Since there's not much code in there, I thought we're not losing that much by not writing ES6.

2017-02-15 20:24 UTC, meirshal commented on lib/nconf-credstash.js
> +    this.cmdArgs.concat(['environemt='+this.environment]);
Not here, it should be like `environment=prod`

2017-02-16 09:37 UTC, meirshal commented on lib/nconf-credstash.js
> +    this.cmdArgs.concat([TABLE_FLAG, this.table]);
done

2017-02-16 09:37 UTC, meirshal commented on lib/nconf-credstash.js
> +    this.cmdArgs.concat(['environemt='+this.environment]);
Actually, it just uses CredStash ability to add "context" as an argument. Context is just pairs of key=value that can be passed as cmd args. I changed it to be more generic.

2017-02-16 09:37 UTC, meirshal commented on lib/nconf-credstash.js
> +Credstash.prototype.get = function (key) {
done

2017-02-16 09:39 UTC, meirshal commented on spec/lib/config.json
> +{
I use this file in nconf-credstash.spec.js, to make sure that the plugin works when using the .file() as well.

2017-02-16 09:39 UTC, meirshal commented on spec/lib/privateMethods.spec.js
> +    it('should add a new key with the specified value', function() {
fixed

2017-02-16 09:39 UTC, meirshal commented on spec/lib/privateMethods.spec.js
> +      Credstash.prototype._insertIntoStore.call(storeHolder, path, value);
That's awesome, really useful for cases like this.

2017-02-16 09:43 UTC, meirshal commented on spec/lib/nconf-credstash.spec.js
> +describe('nconf-credstash', function() {
This depends on how we set up CredStash (the command, not the code). We can solve this problem by running the CI of that package on a slave where CredStash is configured to work with a sandbox that we'll set up, or by using a different DynamoDB table (not as good as the previous solution).

2017-02-16 10:09 UTC, meirshal commented on lib/nconf-credstash.js
> +  path = nconf.path(key); // convert the key (delimited by ':') to a path array.
It really wasn't the best place, it's more relevant to the _getByKey(key) method.
Changed it.

2017-02-16 10:12 UTC, meirshal commented on .gitignore
> +# Logs
Switched to public.

2017-02-19 07:57 UTC, asafdav approved these changes

2017-02-19 07:58 UTC, merged